### ISSUE TITLE
Downsampling support

### ISSUE THREAD

**Issue by leewoosub** [nyu-systems/Grendel-GS#18]
Thank you for a great work!

I have a small question about the image resolution. Original 3DGS support downsampling that downsize the image size if the width is larger than 1.6k, but I found that your code dose not support downsampling.
![Screenshot from 2024-08-08 09-28-29](https://github.com/user-attachments/assets/dd4df80f-e0c7-49ea-8d11-111a718816b3)
Do you have any special intentions? Or is it not implemented?
If there is some reason that multi-gpu 3DGS can't handle downsampling, can you provide a brief explanation please?

**Comment by TarzanZhao** [comment]
By leveraging multiple GPUs' capability, we can directly train at full resolution. We do not have to downsample images when we load them before training. Therefore, we just delete the downsampling code. If you want to use smaller resolution images for training, you can downsample the dataset manually before using Grendel to training them. :)

**Comment by leewoosub** [comment]
I was wondering if downsampling logic affects your work. Now I know that’s not the case, I can add logic with ease. Thanks a lot!

**Comment by BitCalSaul** [comment]
> I was wondering if downsampling logic affects your work. Now I know that’s not the case, I can add logic with ease. Thanks a lot!

Hi I am wondering if you find downsampling logic since I am also spending a long time for high-resolution tasks. Tks :)
