### ISSUE TITLE
online remote SIBR viewer

### ISSUE THREAD

**Issue by cv-lab-x** [nyu-systems/Grendel-GS#21]
hi, thanks for your great work, does the Grendel-gs support remote SIBR viewer during traning as  origin 3DGS?
Looking forward to your reply, thanks.  @TarzanZhao

**Comment by TarzanZhao** [comment]
Hi, sorry, we currently do not support SIBR viewer during training. But theoretically, the distributed system can support this. We are actively developing and may release a more complete toolkit later. Thanks for your suggestion!
