### ISSUE TITLE
Extra Memory Taken on GPU0

### ISSUE THREAD

**Issue by MaureenZOU** [nyu-systems/Grendel-GS#22]
Any people meet with the case that there are many fixed GPU slots used in gpu0 than others. e.g. xueyanz(730M) xueyanz(730M) xueyanz(730M) xueyanz(730M) ...

Thanks!

**Comment by TarzanZhao** [comment]
Hi, do you mean GPU-0 takes up 730MB more memory than other GPUs?

**Comment by TarzanZhao** [comment]
Could you please provide mode details about the issue? Than we may figure it out together :)

**Comment by MaureenZOU** [comment]
So it is the following case:
GPU0 Memory: 2000M + 730M + 730M + 730M
GPU1 Memory: 2000M
GPU2 Memory: 2000M
GPU3 Memory: 2000M
This seems like some communication issue, while GPU0 holds constant redundant memory.

Thanks for the reply!

**Comment by TarzanZhao** [comment]
Hi, by default, args.distributed_dataset_storage is true. This flag enables saving/loading all images from GPU-0 and then broadcast these images to other GPU. That will cause more GPU memory consumption on GPU-0. However, I did not expect that to be as large as 730MB*3 .

**Comment by TarzanZhao** [comment]
@MaureenZOU We can schedule a meeting to figure out this problem together if you think this is important to you? my email is: hz3496@nyu.edu

**Comment by MaureenZOU** [comment]
Thanks so much for your helpful reply! I will check whether it is caused by args.distributed_dataset_storage, as I just tried the standard dataset for use, so that won't be really problematic for now : ) 
Great work BTW!

**Comment by MaureenZOU** [comment]
This is caused by a mystery conda environment bug. Haven't fixed this yet, after the torch.distributed init, those zombie processes will naturally appear. Not related to the great code base.

**Comment by BitCalSaul** [comment]
@TarzanZhao Hi, thank you for the great work!

I have a question regarding args.distributed_dataset_storage = True in the context of the MatrixCity dataset.

In my case, I observed that only rank 0 loads the image data, while the other ranks do not load it, which I believe is expected under this flag.

However, rank 0 does not broadcast the images to other ranks, which causes the other ranks to miss image data entirely, eventually leading to a crash during training.

Is this the intended behavior? Or should there be a broadcast step to ensure all ranks receive the image tensors from rank 0?

Any suggestions or workaround would be much appreciated. Thanks again!
