### ISSUE TITLE
Find a bug while loading matrixcity dataset and fix it

### ISSUE THREAD

**Issue by xinhao-luo** [nyu-systems/Grendel-GS#23]
In scene/dataset_reader.py, line 268:
`with open(os.path.join(path, transformsfile)) as json_file:`

Actually, the 'transformsfile' here is already a complete dataset path because of line 465:
`train_json_path = os.path.join(path, f"transforms_train.json")` 

So,  `os.path.join(path, transformsfile)` will lead to a bug.

And just keep `transformsfile` here will be correct.

**Comment by TarzanZhao** [comment]
Thanks for pointing out!!
