### ISSUE TITLE
compile error for diff-gaussian-rasterization @ 053e6a5

### ISSUE THREAD

**Issue by lt-xiang** [nyu-systems/Grendel-GS#5]
hi, when I build "diff-gaussian-rasterization( 053e6a5 )", there are some errors. Could you provide any solutions ? Before that, I can successfully compile the version used in the original  3D GS.

![image](https://github.com/nyu-systems/Grendel-GS/assets/27660078/d84dfb93-7907-4272-8956-baf102791345)

**Comment by TarzanZhao** [comment]
Hi, could you please try clean all compilation cache and recompile again? I never see this issue before. 

If you still cannot solve this issue, please provide more details of your compilation steps and environment setup. And then we can figure out the solution together.
